### ISSUE TITLE
`cluster.createAutoScalingGroup` fails with "Property AvailabilityZones cannot be empty."

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#289]
Following docs at https://github.com/pulumi/pulumi-awsx/tree/master/nodejs/awsx/ecs#clusters:

```typescript
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const vpc = // ... create custom vpc
const cluster = new awsx.ecs.Cluster("custom", { vpc });

const asg = cluster.createAutoScalingGroup("custom", {
    templateParameters: { minSize: 20 },
    launchConfigurationArgs: { instanceType: "t2.medium" },
});
```

Leads to:

```
error: Plan apply failed: 1 error occurred:
        * creating urn:pulumi:fib-dev-ecs::fib::awsx:x:ecs:Cluster$awsx:x:autoscaling:AutoScalingGroup$aws:cloudformation/stack:Stack::app-asg: ROLLBACK_COMPLETE: ["The following resource(s) failed to create: [Instances]. . Rollback requested by user." "Property AvailabilityZones cannot be empty."]
```

And indeed, the outputted CloudFormation template is missing `AvailabilityZones`:

```yaml
    AWSTemplateFormatVersion: '2010-09-09'
    Outputs:
        Instances:
            Value: !Ref Instances
    Resources:
        Instances:
            Type: AWS::AutoScaling::AutoScalingGroup
            Properties:
                Cooldown: 300
                DesiredCapacity: 2
                HealthCheckGracePeriod: 120
                HealthCheckType: EC2
                LaunchConfigurationName: "app-asg-1ff1dbd"
                MaxSize: 100
                MetricsCollection:
                -   Granularity: 1Minute
                MinSize: 2
                VPCZoneIdentifier: []
                Tags:
                -   Key: Name
                    Value: app-asg
                    PropagateAtLaunch: true
            CreationPolicy:
                ResourceSignal:
                    Count: 2
                    Timeout: PT15M
            UpdatePolicy:
                AutoScalingRollingUpdate:
                    MaxBatchSize: 1
                    MinInstancesInService: 2
                    PauseTime: PT15M
                    SuspendProcesses:
                    -   ScheduledActions
                    WaitOnResourceSignals: true
```
