### ISSUE TITLE
Using Pulumi for ALB instead of K8 manifest files. 

### ISSUE THREAD

**Issue by seivan** [pulumi/pulumi-awsx#637]
## Affected feature
The ability to associate a load balancer with a deployment in EKS via Pulimi instead of deloying K8 manifests or using the AWS Load Balancer Controller. 

I was hoping with the addition of  `TargetGroupBinding` if it's possible using  stuff from https://github.com/pulumi/pulumi-awsx/pull/330 to setup ALB with a Deployment in EKS instead of installing the external controller currently recommended.

**Comment by jaxxstorm** [comment]
Hey @seivan 

You can't actually do this within AWS at all. Kubernetes has cloud controller primitives which allow it to provision loadbalancers which are outside of the scope of awsx

There is a stack overflow answer [here](https://stackoverflow.com/a/48410872/645002) which outlines the steps. I'm going to close this, as it's outside the scope of awsx

**Comment by seivan** [comment]
Apparently you can.
You create an ALB (and associated Listener + Targetgroups) and you use the TargetGroupBinding manifests in K8 to associate your service with the ALB. 

```yaml
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: targetGroupStuff
spec:
  serviceRef:
    name: ServiceForX
    port: 80
  targetGroupARN: ....
```
