### ISSUE TITLE
ECS: Unexpected key 'skipDestroy' found in params

### ISSUE THREAD

**Issue by TalLannder** [pulumi/pulumi-awsx#932]
### What happened?

We recently updated `pulumi/awsx` to `0.40.0` and after running `pulumi up` all the services got a new key `skipDestroy` in the task definition. Looks like this caused our deployment pipelines to fail with the error `ECS: Unexpected key 'skipDestroy' found in params` while using the GIthub action `aws-actions/amazon-ecs-deploy-task-definition@v1`

### Steps to reproduce

Using `pulumi up` create service in AWS ECS.

```
export const fargate = new awsx.ecs.FargateService(
    `${serviceName}-fargate-${stack}`,
    {
      cluster: envEcsCluster,
      subnets: vpcPrivateSubnetIds,
      assignPublicIp: false,
      securityGroups: [ fgSg.id ],
      healthCheckGracePeriodSeconds:180,
      taskDefinitionArgs: {
        containers: {
          featuresService: {
            image: pulumi.interpolate`${registry.repository.repositoryUrl}:latest`,
            memory: 512,
            portMappings: [httpsListener],
            environment: [
              {
                name: "APP_PORT",
                value: "80",
              },
            ],
          },
        },
      },
      waitForSteadyState: false,
      desiredCount: awsEcsServiceDesiredCount,
      tags: {
        app: serviceName,
        env: stack,
      },
    }
);
```

Deploy using:
```
- name: Install pulumi
  uses: pulumi/setup-pulumi@v2
  with:
    pulumi-version: ^3.0.0
  - id: pulumi
  run: |
    pulumi login s3://${{ secrets.pulumi_aws_bucket }}
    pulumi stack select ${{ inputs.stack }}
    # read contents into CI/CD variable
    content=`pulumi stack output -j --show-secrets my_service`
    # write task_definition to json
    pulumi stack output -j --show-secrets my_service | jq .task_definition > ../${{ env.ECS_TASK_DEFINITION }}
    # the following lines are only required for multi line json
    content="${content//'%'/'%25'}"
    content="${content//$'\n'/'%0A'}"
    content="${content//$'\r'/'%0D'}"
    # end of optional handling for multi line json
    echo "::set-output name=my_service::$content"
  working-directory: ./infrastructure-v2/
  env:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    AWS_REGION: 
    PULUMI_CONFIG_PASSPHRASE: 

- name: Fill in the new image ID in the Amazon ECS task definition
  id: task-def
  uses: aws-actions/amazon-ecs-render-task-definition@v1
  with:
    task-definition: ${{ env.ECS_TASK_DEFINITION }}
    container-name: ${{ env.CONTAINER_NAME }}
    image: ${{ fromJson(steps.pulumi.outputs.my_service).repository_url }}:${{ github.sha }}

- name: Deploy Amazon ECS task definition
  uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  with:
    task-definition: ${{ steps.task-def.outputs.task-definition }}
    service: ${{ fromJson(steps.pulumi.outputs.my_service).service }}
    cluster: ${{ fromJson(steps.pulumi.outputs.my_service).cluster }}
    wait-for-service-stability: true
```

### Expected Behavior

New images deployed.

### Actual Behavior

Failure with the message `ECS: Unexpected key 'skipDestroy' found in params`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
