### ISSUE TITLE
Error creating vpc with natGateway strategy "None"

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-awsx#934]
### What happened?

I'm trying to create a VPC like so with no NAT Gateways. It errors

### Steps to reproduce

```
name: ecs_mastdon
runtime: yaml
description: Stand up an ECS cluster with mastodon
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-west-2
configuration:
  vpcNetworkCidr:
    type: String
    default: 172.16.0.0/22
resources:
  # Create a VPC for the EKS cluster
  vpc:
    type: awsx:ec2:Vpc
    properties:
      enableDnsHostnames: true
      cidrBlock: ${vpcNetworkCidr}
      natGateways:
        strategy: "None"
```

### Expected Behavior

It creates a VPC with no NAT gateways

### Actual Behavior

```
Diagnostics:
  pulumi:pulumi:Stack (ecs_mastdon-dev):
    TypeError: Cannot read properties of undefined (reading 'id'): TypeError: Cannot read properties of undefined (reading 'id')
        at /snapshot/awsx/bin/ec2/vpc.js:158:125
        at Array.forEach (<anonymous>)
        at Vpc.initialize (/snapshot/awsx/bin/ec2/vpc.js:97:18)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

    error: an unhandled error occurred: waiting for RPCs: rpc error: code = Unknown desc = Cannot read properties of undefined (reading 'id')
```

### Output of `pulumi about`

```
CLI
Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME  VERSION
awsx  unknown
yaml  unknown

Host
OS       darwin
Version  13.0
Arch     arm64

This project is written in yaml

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/lbrlabs
User           lbrlabs
Organizations  lbrlabs

No dependencies found

Pulumi locates its logs in /var/folders/rk/2c715ngd14jc4c7d3659m7pm0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
