### ISSUE TITLE
Host port not set correctly on awsx fargateservice

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-awsx#935]
### What happened?

I am trying to deploy an ECS fargate service with a container that runs on port 3000, and I'm not able to do so

### Steps to reproduce

YAML

```yaml
  cluster:
    type: aws:ecs:Cluster
  lb:
    type: awsx:lb:ApplicationLoadBalancer
    properties:
      subnetIds: ${vpc.publicSubnetIds}
  mastodon:
    type: awsx:ecs:FargateService
    properties:
      cluster: ${cluster.arn}
      taskDefinitionArgs:
        container:
          image: tootsuite/mastodon
          cpu: 256
          memory: 128
          # environment:
          #   - name: LOCAL_DOMAIN
          #     value: "mastodon.lbrlabs.com"
          #   - name: "DB_HOST"
          #     value: ${db.address}
          #   - name: "DB_USER"
          #     value: ${db.username}
          #   - name: "DB_PASSWORD"
          #     value: ${password.result}
          portMappings:
            - containerPort: 3000
              targetGroup: ${lb.defaultTargetGroup}   
              hostPort: 3000
```

### Expected Behavior

It creates the container

### Actual Behavior

```
  aws:ecs:TaskDefinition (mastodon):
    error: 1 error occurred:
    	* failed creating ECS Task Definition (mastodon-3c77ecac): ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match.
    	* ```

### Output of `pulumi about`

_No response_

### Additional context

I can see in the diff that the `hostPort` never gets set

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
